export const ignorePatterns = [
  "**/.source/**",
  "**/.next/**",
  "**/.turbo/**",
  "**/.vercel/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**",
  "**/out/**",
  "**/node_modules/**",
  "**/_artifacts/**",
  "**/next-env.d.ts",
  "**/*.gen.ts",
  "**/*.generated.ts",
  "examples/svelte/src/lib/index.ts",
  "pnpm-lock.yaml",
];
