import type { OxlintConfig } from 'oxlint'
import { defineConfig } from 'oxlint'

import { ignorePatterns } from './ignores.ts'

const nonReactGlobs = [
  'permix/src/vue/**',
  'permix/src/solid/**',
  'permix/src/svelte/**',
  'examples/vue/**',
  'examples/solid/**',
  'examples/svelte/**',
]

export default defineConfig({
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'node',
    'promise',
    'react',
    'vue',
  ],
  env: {
    browser: true,
    node: true,
  },
  categories: {
    correctness: 'error',
    suspicious: 'error',
    perf: 'off',
  },
  options: {
    typeAware: true,
  },
  ignorePatterns,
  settings: {
    next: {
      rootDir: ['examples/next'],
    },
  },
  rules: {
    'no-console': 'off',
    'no-shadow': 'off',
    'import/no-unassigned-import': 'off',
    'import/namespace': 'off',
    'jsdoc/check-tag-names': 'off',
    'promise/always-return': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'no-duplicate-imports': [
      'error',
      {
        allowSeparateTypeImports: true,
      },
    ],
    'no-underscore-dangle': [
      'error',
      {
        allow: ['_splat', '_INVALID'],
      },
    ],
    'rules-of-hooks': 'error',
    'react/only-export-components': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-filename-extension': 'off',
    'react/no-unknown-property': 'off',
    'react/error-boundaries': 'error',
    'react/globals': 'error',
    'react/immutability': 'error',
    'react/incompatible-library': 'error',
    'react/preserve-manual-memoization': 'error',
    'react/purity': 'error',
    'react/refs': 'error',
    'react/set-state-in-effect': 'error',
    'react/set-state-in-render': 'error',
    'react/static-components': 'error',
    'react/use-memo': 'error',
    'react/void-use-memo': 'error',
    'react/unsupported-syntax': 'off',
    'react/no-deriving-state-in-effects': 'off',
    'react/invariant': 'off',
    'react/rule-suppression': 'off',
    'react/syntax': 'off',
    'react/todo': 'off',
    'react/capitalized-calls': 'off',
    'react/exhaustive-effect-dependencies': 'off',
    'react/hooks': 'off',
    'react/memo-dependencies': 'off',
    'typescript/await-thenable': 'error',
    'typescript/consistent-type-imports': 'error',
    'typescript/no-explicit-any': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-unsafe-argument': 'off',
    'typescript/no-unsafe-assignment': 'off',
    'typescript/no-unsafe-call': 'off',
    'typescript/no-unsafe-member-access': 'off',
    'typescript/no-unsafe-return': 'off',
    'typescript/only-throw-error': 'off',
    'typescript/return-await': ['error', 'always'],
    'typescript/strict-boolean-expressions': 'off',
    'typescript/switch-exhaustiveness-check': 'error',
    'typescript/unbound-method': 'off',
    'typescript/consistent-return': 'off',
    'typescript/no-base-to-string': 'off',
    'typescript/no-misused-spread': 'off',
    'typescript/no-redundant-type-constituents': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/no-unnecessary-type-conversion': 'off',
    'typescript/no-unnecessary-type-parameters': 'off',
    'typescript/no-useless-default-assignment': 'off',
  },
  overrides: [
    {
      files: nonReactGlobs,
      rules: {
        'rules-of-hooks': 'off',
        'react/error-boundaries': 'off',
        'react/globals': 'off',
        'react/immutability': 'off',
        'react/incompatible-library': 'off',
        'react/preserve-manual-memoization': 'off',
        'react/purity': 'off',
        'react/refs': 'off',
        'react/set-state-in-effect': 'off',
        'react/set-state-in-render': 'off',
        'react/static-components': 'off',
        'react/use-memo': 'off',
        'react/void-use-memo': 'off',
        'react/jsx-key': 'off',
      },
    },
    {
      files: [
        'permix/**/*.{test,spec}.{ts,tsx,js,jsx}',
        'examples/tanstack-start/**/*.{test,spec}.{ts,tsx,js,jsx}',
      ],
      plugins: ['vitest'],
      rules: {
        'vitest/expect-expect': 'off',
        'vitest/no-focused-tests': 'error',
        'vitest/no-identical-title': 'error',
        'vitest/valid-expect': 'error',
        'vitest/require-mock-type-parameters': 'off',
        'vitest/require-to-throw-message': 'off',
        'no-empty-function': 'off',
        'react/globals': 'off',
        'typescript/consistent-type-imports': 'off',
      },
    },
    {
      files: ['examples/next/**/*.{js,jsx,ts,tsx,mjs,cjs}'],
      plugins: ['nextjs'],
      rules: {
        '@next/next/no-async-client-component': 'error',
        '@next/next/no-css-tags': 'error',
        '@next/next/no-head-element': 'error',
        '@next/next/no-img-element': 'error',
        '@next/next/no-sync-scripts': 'error',
        '@next/next/inline-script-id': 'error',
      },
    },
  ],
}) satisfies OxlintConfig
