/* This file is generated by Permix. Do not edit it directly. */
import {
  createPermissionConfig,
  createPermissionOverlay,
} from 'permix'
import type {
  ApplyPermissionOverlay,
  Definition as PermixDefinition,
} from 'permix'

export type { PermissionReference } from 'permix/extractor'

export const permissionKeys = [
  'tasks.comment',
  'tasks.delete',
  'tasks.read',
  'workspace.members.invite',
] as const

export type Permission = (typeof permissionKeys)[number]

export const permissions = {
  tasks: {
    comment: 'tasks.comment',
    delete: 'tasks.delete',
    read: 'tasks.read',
  },
  workspace: {
    members: {
      invite: 'workspace.members.invite',
    },
  },
} as const

export const permissionMetadata = {
  'tasks.comment': {
    title: 'Comment on a task',
    description: 'Add comments from the task page, public API, or an AI tool.',
    tags: [
      'tasks',
      'collaboration',
    ],
    annotations: {
      area: 'work-management',
      risk: 'standard',
      surfaces: [
        'task-page',
        'api',
        'ai-tool',
      ],
    },
  },
  'tasks.delete': {
    title: 'Delete a task',
    description: 'Permanently delete a task.',
    annotations: {
      area: 'work-management',
      risk: 'elevated',
      surfaces: [
        'task-page',
        'api',
      ],
    },
  },
  'tasks.read': {
    title: 'Read tasks',
  },
  'workspace.members.invite': {
    title: 'Invite workspace members',
    annotations: {
      area: 'organization',
      risk: 'elevated',
    },
  },
} as const

export const permissionDefinition = {
  tasks: [
    'comment',
    'delete',
    'read',
  ],
  workspace: {
    members: [
      'invite',
    ],
  },
} as const

export type ExtractedDefinition = typeof permissionDefinition

export type Definition<
  Overlay extends PermixDefinition = ExtractedDefinition,
> = ApplyPermissionOverlay<ExtractedDefinition, Overlay>

export const definePermissionConfig =
  createPermissionConfig<Permission>()

export const definePermissionOverlay =
  createPermissionOverlay<ExtractedDefinition>()
