import fs from 'node:fs';
import path from 'node:path';

const currentDir = import.meta.dirname;
const srcDir = path.join(currentDir, '..', 'src');
const svelteDist = path.join(currentDir, '..', 'dist', 'svelte');

if (!fs.existsSync(svelteDist)) {
  throw new Error(
    '[Permix]: dist/svelte not found. Run `svelte-package` before this script.'
  );
}

/**
 * `svelte-package` emits `.d.ts` files for cross-boundary imports (e.g. `../core`)
 * directly into the source tree. Remove these stray declaration files — the real
 * types are generated by `tsdown` into `dist`.
 */
function removeStraySourceTypes(dir: string) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      removeStraySourceTypes(fullPath);
      continue;
    }

    if (entry.name.endsWith('.d.ts')) {
      fs.rmSync(fullPath, { force: true });
    }
  }
}

/**
 * Remove test and fixture artifacts that `svelte-package` copies from `src/svelte`.
 */
function cleanup(dir: string) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (entry.name === '__fixtures__') {
        fs.rmSync(fullPath, { recursive: true, force: true });
        continue;
      }
      cleanup(fullPath);
      continue;
    }

    if (/\.test\.(?:js|ts|d\.ts)$/.test(entry.name)) {
      fs.rmSync(fullPath, { force: true });
    }
  }
}

/**
 * Rewrite bare `../core` imports to the explicit `../core/index.mjs` file that
 * `tsdown` emits, so the shipped Svelte files resolve in strict ESM and TS.
 */
function rewriteCoreImports(dir: string) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      rewriteCoreImports(fullPath);
      continue;
    }

    if (!/\.(?:js|svelte|d\.ts)$/.test(entry.name)) {
      continue;
    }

    const content = fs.readFileSync(fullPath, 'utf-8');
    const rewritten = content.replaceAll(
      /(['"])\.\.\/core\1/g,
      '$1../core/index.mjs$1'
    );

    if (rewritten !== content) {
      fs.writeFileSync(fullPath, rewritten);
    }
  }
}

cleanup(svelteDist);
rewriteCoreImports(svelteDist);
removeStraySourceTypes(srcDir);
