name: Build and publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          install: false
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run publish
        env:
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'
          NPM_CONFIG_PROVENANCE: true
